# Workflow to publish the content from the main branch to the site branch,
# which is used to deploy the Astro site to GitHub Pages.

name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Publish to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions[Bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Copy the content from the main branch to the site branch
          [ -d ./content ] && cp -r ./content ./src/src/content
          [ -d ./src/src/content ] && git add ./src/src/content
          git add ./.github
          git commit -m "Publish content to GitHub Pages"
          git push origin main:site
          git rm -rf ./src/src/content
